# Generated by Django 2.2.1 on 2019-09-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticles',
            name='color',
            field=models.CharField(choices=[('success', 'green'), ('warning', 'yellow'), ('danger', 'red'), ('dark', 'black'), ('light', 'white'), ('info', 'blue')], default='green', max_length=10, verbose_name='Цвет'),
        ),
    ]
