# Generated by Django 2.2.1 on 2019-09-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190921_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myarticles',
            name='coments',
        ),
        migrations.AddField(
            model_name='coments',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Main.MyArticles'),
            preserve_default=False,
        ),
    ]
