# Generated by Django 2.2.5 on 2019-11-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190921_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coments',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AddField(
            model_name='myarticles',
            name='html_text',
            field=models.TextField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
