# Generated by Django 2.2.5 on 2019-11-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20191109_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myarticles',
            old_name='html_text',
            new_name='html',
        ),
    ]
