# Generated by Django 2.2.5 on 2019-11-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20191109_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myarticles',
            old_name='html',
            new_name='html_text',
        ),
    ]
